export const AcademicResults = [
  {
    term: "1/2565",
    sub_id: "30000-1101",
    sub_name: "ทักษะภาษาไทยเชิงวิชาชีพ",
    theory: "3",
    practical: "0",
    credit: "3",
    level: "4",
    note: "",
  },
  {
    term: "1/2565",
    sub_id: "30000-1501",
    sub_name: "ชีวิตกับสังคมไทย",
    theory: "3",
    practical: "0",
    credit: "3",
    level: "4",
    note: "",
  },
  {
    term: "1/2565",
    sub_id: "30000-2001",
    sub_name: "กิจกรรมองค์การวิชาชีพ 1",
    theory: "0",
    practical: "2",
    credit: "0",
    level: "ผ.",
    note: "",
  },
  {
    term: "1/2565",
    sub_id: "30001-2001",
    sub_name: "เทคโนโลยีสารสนเทศเพื่อการจัดการอาชีพ",
    theory: "2",
    practical: "2",
    credit: "3",
    level: "4",
    note: "",
  },
  {
    term: "1/2565",
    sub_id: "30901-1003",
    sub_name: "ระบบฐานข้อมูลและการออกแบบ",
    theory: "1",
    practical: "4",
    credit: "3",
    level: "4",
    note: "",
  },
  {
    term: "1/2565",
    sub_id: "30901-2405",
    sub_name: "พื้นฐานการผลิตคอมพิวเตอร์เกมและแอนิเมชัน",
    theory: "1",
    practical: "4",
    credit: "3",
    level: "4",
    note: "",
  },
  {
    term: "1/2565",
    sub_id: "30901-1002",
    sub_name: "การออกแบบและพัฒนาเว็บไซต์",
    theory: "1",
    practical: "4",
    credit: "3",
    level: "4",
    note: "",
  },
  {
    term: "1/2565",
    sub_id: "30901-2001",
    sub_name: "โครงสร้างข้อมูลและอัลกอริทึม",
    theory: "1",
    practical: "4",
    credit: "3",
    level: "4",
    note: "",
  },
  {
    term: "2/2565",
    sub_id: "30000-1201",
    sub_name: "ภาษาอังกฤษเพื่อการสื่อสาร",
    theory: "2",
    practical: "2",
    credit: "3",
    level: "4",
    note: "",
  },
  {
    term: "2/2565",
    sub_id: "30000-2002",
    sub_name: "กิจกรรมองค์การวิชาชีพ 2",
    theory: "0",
    practical: "2",
    credit: "0",
    level: "ผ.",
    note: "",
  },
  {
    term: "2/2565",
    sub_id: "30901-1001",
    sub_name: "การโปรแกรมคอมพิวเตอร์เชิงโครงสร้าง",
    theory: "1",
    practical: "4",
    credit: "3",
    level: "4",
    note: "",
  },
  {
    term: "2/2565",
    sub_id: "30000-1404",
    sub_name: "แคลคูลัส 1",
    theory: "3",
    practical: "0",
    credit: "3",
    level: "4",
    note: "",
  },
  {
    term: "2/2565",
    sub_id: "30901-2003",
    sub_name: "การพัฒนาระบบฐานข้อมูล",
    theory: "1",
    practical: "4",
    credit: "3",
    level: "4",
    note: "",
  },
  {
    term: "2/2565",
    sub_id: "30901-2008",
    sub_name: "การพัฒนาเว็บด้วยภาษา PHP",
    theory: "1",
    practical: "4",
    credit: "3",
    level: "4",
    note: "",
  },
  {
    term: "2/2565",
    sub_id: "30901-2121",
    sub_name: "เทคโนโลยีเว็บสำเร็จรูป",
    theory: "1",
    practical: "4",
    credit: "3",
    level: "4",
    note: "",
  },
  {
    term: "3/2565",
    sub_id: "30901-8001",
    sub_name: "ฝึกงาน",
    theory: "0",
    practical: "320",
    credit: "4",
    level: "4",
    note: "",
  },
  {
    term: "1/2566",
    sub_id: "30000-1203",
    sub_name: "การสนทนาภาษาอังกฤษในสถานประกอบการ",
    theory: "1",
    practical: "2",
    credit: "2",
    level: "4",
    note: "",
  },
  {
    term: "1/2566",
    sub_id: "30000-1303",
    sub_name: "วิทยาศาสตร์งานไฟฟ้า อิเล็กทรอนิกส์ และการสื่อสาร",
    theory: "2",
    practical: "2",
    credit: "3",
    level: "4",
    note: "",
  },
  {
    term: "1/2566",
    sub_id: "30000-1610",
    sub_name: "นันทนาการเพื่อพัฒนาคุณภาพชีวิต",
    theory: "0",
    practical: "2",
    credit: "1",
    level: "4",
    note: "",
  },
  {
    term: "1/2566",
    sub_id: "30901-2002",
    sub_name: "การวิเคราะห์และออกแบบเชิงวัตถุ",
    theory: "1",
    practical: "4",
    credit: "3",
    level: "4",
    note: "",
  },
  {
    term: "1/2566",
    sub_id: "30901-2004",
    sub_name: "ระบบปฏิบัติการเครื่องแม่ข่าย",
    theory: "1",
    practical: "4",
    credit: "3",
    level: "4",
    note: "",
  },
  {
    term: "1/2566",
    sub_id: "30901-2005",
    sub_name: "การโปรแกรมเชิงวัตถุด้วยเทคโนโลยีจาวา",
    theory: "1",
    practical: "4",
    credit: "3",
    level: "4",
    note: "",
  },
  {
    term: "1/2566",
    sub_id: "30901-2017",
    sub_name: "พื้นฐานเทคโนโลยีระบบสมองกลฝังตัวและไอโอที",
    theory: "1",
    practical: "4",
    credit: "3",
    level: "4",
    note: "",
  },
  {
    term: "1/2566",
    sub_id: "30901-8502",
    sub_name: "โครงงาน 1",
    theory: "0",
    practical: "2",
    credit: "2",
    level: "4",
    note: "",
  },

  {
    term: "1/2566",
    sub_id: "30000-2003",
    sub_name: "กิจกรรมองค์การวิชาชีพ 3",
    theory: "0",
    practical: "2",
    credit: "0",
    level: "ผ.",
    note: "",
  },
];
